title: Alex ⚡️ Blogs
title_separator: "-"
email: alex.bohdjalian@gmail.com
description: >-
  Welcome to my portfolio! I am a Software Developer with a passion for creating
  robust and performant applications. I am currently working as a Software
  Developer at Mayden, a healthcare software company based in Bath, UK.
github_username: AlexBohdjalian
minimal_mistakes_skin: dark
search: true

logo: "/assets/images/logo.png"

copyright: "Alex Bohdjalian"

locale: en_GB

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

domain: alexbohdjalian.com
url: https://alexbohdjalian.com

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alex Bohdjalian"
  avatar : "/assets/images/bio-photo.png"
  bio: "Passionate about elegant, robust and performant web applications."
  location: "Portishead, UK"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alex-bohdjalian"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexbohdjalian"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:alexandros11@hotmail.co.uk"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alex-bohdjalian"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/alexbohdjalian"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:alexandros11@hotmail.co.uk"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/
